apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-page-deployment
spec:
  selector:
    matchLabels:
      app: static-page
  replicas: 2
  template:
    metadata:
      labels:
        app: static-page
    spec:
      containers:
      - name: static-page
        image: pradeepkmr/nginx-webserver-html:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-page-service
  labels:
    app: static-page
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: static-page
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-page-ingress
  namespace: kube-system
spec:
  rules:
  - host: static-page.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: static-page-service
            port:
              number: 80
